# This workflow will be triggered on every merge on the main branch
# Note : if the metainfo.prop file is not present, the job is canceled

# To get started, configure the following in your repos secrets https://docs.github.com/en/actions/security-guides/encrypted-secrets
# SOLACE_CLOUD_TOKEN: Solace Cloud Token

name: Config Push Deploy
on:
  push: 
    branches: [ main ]

env:
  EVENT_MESH_NAME: us-central-solace-Prod
  
jobs:
  config-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Get all changed markdown files
        id: changed-markdown-files
        uses: tj-actions/changed-files@v40
        with:
          files: | 
            metainfo.prop
      
      - name: Read metainfo.prop content
        id: metadata
        run: |
          for file in ${{ steps.changed-markdown-files.outputs.all_changed_files }}; do
            echo 'meta<<EOF' >> $GITHUB_OUTPUT
            echo $(cat $file) >> $GITHUB_OUTPUT
            echo 'EOF' >> $GITHUB_OUTPUT
          done
      
      - name: Extract Application Version ID from metainfo.prop
        if: ${{ steps.metadata.outputs.meta }}
        uses: tmelliottjr/extract-regex-action@v1.4.0
        id: epApplicationVersionId
        with:
          regex: '(?<=applicationVersionID=)(?!.*=).*' 
          flags: "gm"
          input: ${{steps.metadata.outputs.meta}}

      - name: Promote Application Version
        if: ${{ steps.epApplicationVersionId.outputs.resultString }}
        uses: SolaceDev/solace-ep-config-push@v0.1.0
        with:
          SOLACE_CLOUD_TOKEN: ${{ secrets.SOLACE_CLOUD_TOKEN }}
          APPLICATION_VERSION_ID: ${{ steps.epApplicationVersionId.outputs.resultString }}
          EVENT_MESH_NAME: ${{ env.EVENT_MESH_NAME }}
